mnmn: SmartThingsCommunity
vid: REPLACE_WITH_VID
version: 0.0.1
type: profile
dashboard:
  states:
    - component: main
      capability: temperatureMeasurement
      version: 1
      idx: 0
      group: Temperature
      values: []
      composite: false
    - component: main
      capability: relativeHumidityMeasurement
      version: 1
      idx: 0
      group: Humidity
      values: []
      composite: false
    - component: main
      capability: battery
      version: 1
      idx: 0
      group: Battery
      values: []
      composite: false
  actions:
    - component: main
      capability: refresh
      version: 1
      idx: 0
      group: Refresh
      inline: null
  basicPlus: []
detailView:
  - component: main
    capability: temperatureMeasurement
    version: 1
    values: []
    patch: []
  - component: main
    capability: relativeHumidityMeasurement
    version: 1
    values: []
    patch: []
  - component: main
    capability: battery
    version: 1
    values: []
    patch: []
  - component: main
    capability: refresh
    version: 1
    values: []
    patch: []
automation:
  conditions:
    - component: main
      capability: temperatureMeasurement
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: relativeHumidityMeasurement
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: battery
      version: 1
      values: []
      patch: []
      exclusion: []
  actions: []
