mnmn: SmartThingsCommunity
vid: REPLACE_WITH_VID
version: 0.0.1
type: profile
dashboard:
  states:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: Switch 1
      values: []
      composite: true
    - component: l2
      capability: switch
      version: 1
      idx: 0
      group: Switch 2
      values: []
      composite: true
    - component: l3
      capability: switch
      version: 1
      idx: 0
      group: Switch 3
      values: []
      composite: true
    - component: main
      capability: powerMeter
      version: 1
      idx: 0
      group: Power
      values: []
      composite: false
  actions:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: Switch 1
      inline: null
    - component: l2
      capability: switch
      version: 1
      idx: 0
      group: Switch 2
      inline: null
    - component: l3
      capability: switch
      version: 1
      idx: 0
      group: Switch 3
      inline: null
  basicPlus: []
detailView:
  - component: main
    capability: switch
    version: 1
    values: []
    patch: []
  - component: main
    capability: powerMeter
    version: 1
    values: []
    patch: []
  - component: main
    capability: energyMeter
    version: 1
    values: []
    patch: []
  - component: main
    capability: voltageMeasurement
    version: 1
    values: []
    patch: []
  - component: main
    capability: currentMeasurement
    version: 1
    values: []
    patch: []
  - component: l2
    capability: switch
    version: 1
    values: []
    patch: []
  - component: l3
    capability: switch
    version: 1
    values: []
    patch: []
  - component: main
    capability: refresh
    version: 1
    values: []
    patch: []
automation:
  conditions:
    - component: main
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: l2
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: l3
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: powerMeter
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: energyMeter
      version: 1
      values: []
      patch: []
      exclusion: []
  actions:
    - component: main
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: l2
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: l3
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
